// react/pages/hacker-news/top/[page].js
import fetch from 'isomorphic-unfetch';
import Head from 'next/head';
import Summary from '../../../components/Summary';

const PAGE_SIZE = 30;

function Page({ items, page }) {
  const start = 1 + (Number(page) - 1) * PAGE_SIZE;
  const next = `/hacker-news/top/${Number(page) + 1}`;

  return (
    <>
      <style jsx>{`
        a {
          padding: 2em;
          display: block;
        }
      `}</style>

      <Head>
        <title>Hacker News</title>
      </Head>

      {items.map((item, i) => (
        <Summary item={item} index={start + i} key={start + i} />
      ))}
      {next && (
        <a className="more" href={next}>
          More...
        </a>
      )}
    </>
  );
}

Page.getInitialProps = async ({ query }) => {
  const { page } = query;
  const res = await fetch(`https://node-hnapi.herokuapp.com/news?page=${page}`);
  const items = await res.json();
  return { items, page };
};

export default Page;

// svelte/src/routes/hacker-news/top/[page].svelte
<script context="module">
  export async function preload({ params }, session) {
    const { page } = params;
    const res = await this.fetch(
      `https://node-hnapi.herokuapp.com/news?page=${page}`
    );
    const items = await res.json();
    const offset = Number(page) * PAGE_SIZE;
    return { page, items };
  }
</script>

<script>
  import Summary from "./_Summary.svelte";

  const PAGE_SIZE = 30;

  export let page;
  export let items;

  $: start = 1 + (Number(page) - 1) * PAGE_SIZE;
  $: next = `/hacker-news/top/${Number(page) + 1}`;
</script>

<style>
  a {
    padding: 2em;
    display: block;
  }
</style>

<svelte:head>
  <title>Hacker News</title>
</svelte:head>

{#each items as item, i}
  <Summary {item} index={start + i} />
{/each}

{#if next}
  <a class="more" href={next}>More...</a>
{/if}
