// vue/pages/crud/index.vue
<template>
  <div>
    <input placeholder="filter prefix" v-model="prefix" />

    <select :value="i" size="5" @change="select">
      <option v-for="(person, i) in filteredPeople" :value="i" :key="i">{{ person.last }}, {{ person.first }}</option>
    </select>

    <label>
      <input v-model="first" placeholder="first" />
    </label>
    <label>
      <input v-model="last" placeholder="last" />
    </label>

    <div class="buttons">
      <button @click="create" :disabled="!first || !last">create</button>
      <button @click="update" :disabled="!first || !last || !selected">update</button>
      <button @click="remove" :disabled="!selected">delete</button>
    </div>
  </div>
</template>

<script>
  export default {
    name: 'CRUD',
    components: {},

    head() {
      return {
        title: 'CRUD'
      };
    },

    data: () => {
      return {
        people: [
          {
            first: 'Hans',
            last: 'Emil'
          },
          {
            first: 'Max',
            last: 'Mustermann'
          },
          {
            first: 'Roman',
            last: 'Tisch'
          }
        ],
        i: 0,
        prefix: '',
        first: '',
        last: ''
      };
    },

    computed: {
      filteredPeople: function() {
        const { prefix, people } = this;
        return prefix
          ? people.filter(person => {
              const name = `${person.last}, ${person.first}`;
              return name.toLowerCase().startsWith(prefix.toLowerCase());
            })
          : people;
      },
      selected: function() {
        return this.filteredPeople[this.i];
      }
    },

    watch: {
      i: function() {
        this.first = this.selected ? this.selected.first : '';
        this.last = this.selected ? this.selected.last : '';
      },
      prefix: function() {
        this.first = this.selected ? this.selected.first : '';
        this.last = this.selected ? this.selected.last : '';
      }
    },

    methods: {
      select: function(event) {
        this.i = Number(event.target.value);
      },
      create: function() {
        this.people.push({ first: this.first, last: this.last });
        this.i = this.people.length - 1;
      },
      update: function(person) {
        this.people[this.i] = { first: this.first, last: this.last };
        this.people = [...this.people];
      },
      remove: function() {
        const index = this.people.indexOf(this.selected);
        this.people.splice(index, 1);
        this.i = Math.min(this.i, this.filteredPeople.length - 1);
      }
    }
  };
</script>

<style lang="stylus" scoped>
  * {
    font-family: inherit;
    font-size: inherit;
  }

  input {
    display: block;
    margin: 0 0 0.5em 0;
  }

  select {
    float: left;
    margin: 0 1em 1em 0;
    width: 14em;
  }

  .buttons {
    clear: both;
  }
</style>

// react/pages/crud/index.js
import { useState, useEffect } from 'react';
import Head from 'next/head';

const initialPeople = [
  {
    first: 'Hans',
    last: 'Emil'
  },
  {
    first: 'Max',
    last: 'Mustermann'
  },
  {
    first: 'Roman',
    last: 'Tisch'
  }
];

export default () => {
  const [{ people, selected }, setPeople] = useState({ people: initialPeople, selected: 0 });
  const [prefix, setPrefix] = useState('');
  const [first, setFirst] = useState('');
  const [last, setLast] = useState('');
  const [selectedPerson, setSelectedPerson] = useState(people[selected]);

  const filteredPeople = prefix
    ? people.filter(person => {
        const name = `${person.last}, ${person.first}`;
        return name.toLowerCase().startsWith(prefix.toLowerCase());
      })
    : people;

  useEffect(() => {
    const selectedPerson = filteredPeople[selected];
    setFirst(selectedPerson ? selectedPerson.first : '');
    setLast(selectedPerson ? selectedPerson.last : '');
    setSelectedPerson(selectedPerson);
  }, [selected, filteredPeople.length]);

  const update = () => {
    people[selected] = { first, last };
    setPeople({ people: [...people], selected: selected });
  };

  const create = () => setPeople({ people: [...people, { first, last }], selected: people.length });

  const remove = () => {
    const index = people.indexOf(selectedPerson);
    setPeople({
      people: [...people.slice(0, index), ...people.slice(index + 1)],
      selected: Math.min(selected, filteredPeople.length - 2)
    });
  };

  const select = selected => setPeople({ people, selected });

  return (
    <>
      <style jsx>{`
        * {
          font-family: inherit;
          font-size: inherit;
        }

        input {
          display: block;
          margin: 0 0 0.5em 0;
        }

        select {
          float: left;
          margin: 0 1em 1em 0;
          width: 14em;
        }

        .buttons {
          clear: both;
        }
      `}</style>

      <Head>
        <title>CRUD</title>
      </Head>

      <input placeholder="filter prefix" value={prefix} onChange={event => setPrefix(event.target.value)} />

      <select size={5} value={selected} onChange={event => select(Number(event.target.value))}>
        {filteredPeople.map((person, i) => (
          <option value={i} key={i}>
            {person.last}, {person.first}
          </option>
        ))}
      </select>

      <label>
        <input value={first} placeholder="first" onChange={event => setFirst(event.target.value)} />
      </label>
      <label>
        <input value={last} placeholder="last" onChange={event => setLast(event.target.value)} />
      </label>

      <div className="buttons">
        <button onClick={create} disabled={!first || !last}>
          create
        </button>
        <button onClick={update} disabled={!first || !last || !selectedPerson}>
          update
        </button>
        <button onClick={remove} disabled={!selectedPerson}>
          delete
        </button>
      </div>
    </>
  );
};
