// svelte/src/routes/crud/index.svelte
<script>
  // Taken from https://svelte.dev/examples#7guis-crud

  let people = [
    {
      first: 'Hans',
      last: 'Emil'
    },
    {
      first: 'Max',
      last: 'Mustermann'
    },
    {
      first: 'Roman',
      last: 'Tisch'
    }
  ];

  let prefix = '';
  let first = '';
  let last = '';
  let i = 0;

  $: filteredPeople = prefix
    ? people.filter(person => {
        const name = `${person.last}, ${person.first}`;
        return name.toLowerCase().startsWith(prefix.toLowerCase());
      })
    : people;

  $: selected = filteredPeople[i];

  $: reset_inputs(selected);

  function create() {
    people = people.concat({ first, last });
    i = people.length - 1;
    first = last = '';
  }

  function update() {
    people[i] = { first, last };
  }

  function remove() {
    // Remove selected person from the source array (people), not the filtered array
    const index = people.indexOf(selected);
    people = [...people.slice(0, index), ...people.slice(index + 1)];

    first = last = '';
    i = Math.min(i, filteredPeople.length - 2);
  }

  function reset_inputs(person) {
    first = person ? person.first : '';
    last = person ? person.last : '';
  }
</script>

<style>
  * {
    font-family: inherit;
    font-size: inherit;
  }

  input {
    display: block;
    margin: 0 0 0.5em 0;
  }

  select {
    float: left;
    margin: 0 1em 1em 0;
    width: 14em;
  }

  .buttons {
    clear: both;
  }
</style>

<svelte:head>
  <title>CRUD</title>
</svelte:head>

<input placeholder="filter prefix" bind:value={prefix} />

<select bind:value={i} size={5}>
  {#each filteredPeople as person, i}
    <option value={i}>{person.last}, {person.first}</option>
  {/each}
</select>

<label>
  <input bind:value={first} placeholder="first" />
</label>
<label>
  <input bind:value={last} placeholder="last" />
</label>

<div class="buttons">
  <button on:click={create} disabled={!first || !last}>create</button>
  <button on:click={update} disabled={!first || !last || !selected}>update</button>
  <button on:click={remove} disabled={!selected}>delete</button>
</div>

// vue/pages/crud/index.vue
<template>
  <div>
    <input placeholder="filter prefix" v-model="prefix" />

    <select :value="i" size="5" @change="select">
      <option v-for="(person, i) in filteredPeople" :value="i" :key="i">{{ person.last }}, {{ person.first }}</option>
    </select>

    <label>
      <input v-model="first" placeholder="first" />
    </label>
    <label>
      <input v-model="last" placeholder="last" />
    </label>

    <div class="buttons">
      <button @click="create" :disabled="!first || !last">create</button>
      <button @click="update" :disabled="!first || !last || !selected">update</button>
      <button @click="remove" :disabled="!selected">delete</button>
    </div>
  </div>
</template>

<script>
  export default {
    name: 'CRUD',
    components: {},

    head() {
      return {
        title: 'CRUD'
      };
    },

    data: () => {
      return {
        people: [
          {
            first: 'Hans',
            last: 'Emil'
          },
          {
            first: 'Max',
            last: 'Mustermann'
          },
          {
            first: 'Roman',
            last: 'Tisch'
          }
        ],
        i: 0,
        prefix: '',
        first: '',
        last: ''
      };
    },

    computed: {
      filteredPeople: function() {
        const { prefix, people } = this;
        return prefix
          ? people.filter(person => {
              const name = `${person.last}, ${person.first}`;
              return name.toLowerCase().startsWith(prefix.toLowerCase());
            })
          : people;
      },
      selected: function() {
        return this.filteredPeople[this.i];
      }
    },

    watch: {
      i: function() {
        this.first = this.selected ? this.selected.first : '';
        this.last = this.selected ? this.selected.last : '';
      },
      prefix: function() {
        this.first = this.selected ? this.selected.first : '';
        this.last = this.selected ? this.selected.last : '';
      }
    },

    methods: {
      select: function(event) {
        this.i = Number(event.target.value);
      },
      create: function() {
        this.people.push({ first: this.first, last: this.last });
        this.i = this.people.length - 1;
      },
      update: function(person) {
        this.people[this.i] = { first: this.first, last: this.last };
        this.people = [...this.people];
      },
      remove: function() {
        const index = this.people.indexOf(this.selected);
        this.people.splice(index, 1);
        this.i = Math.min(this.i, this.filteredPeople.length - 1);
      }
    }
  };
</script>

<style lang="stylus" scoped>
  * {
    font-family: inherit;
    font-size: inherit;
  }

  input {
    display: block;
    margin: 0 0 0.5em 0;
  }

  select {
    float: left;
    margin: 0 1em 1em 0;
    width: 14em;
  }

  .buttons {
    clear: both;
  }
</style>
